### ISSUE TITLE
[Feature request] 1.19.2 version

### ISSUE THREAD

**Issue by Rozbiynk** [Wesley1808/AdvancedChat#1]
Hello, can you backport your mod to 1.19.2? I use it version because many my mods dont update to 1.19.3

**Comment by ysefwakil** [comment]
Bump

**Comment by Wesley1808** [comment]
Sorry for the late response. 

There's a 1.19.2 branch you could compile yourself if you want to right now (action builds expired) but its a bit outdated and I can't guarantee it working perfectly mainly because of 1.19.2 chat reporting being more aggressive than 1.19.3+

When I get some time and some motivation to properly backport newer versions to 1.19.2 is unclear atm.

**Comment by Rozbiynk** [comment]
okay, thank

**Comment by Rozbiynk** [comment]
Im lame, so can you help with compiling mod? i dont know, where it after run gradle

**Comment by Wesley1808** [comment]
Where the compiled jar is after running gradlew build? It'll be in `build/libs`

**Comment by Rozbiynk** [comment]
thank
